# Example: Overlay Network Subnet
# 
# 此示例创建一个 Overlay 网络子网，用于 Pod IP 分配。
# Overlay 网络使用 VXLAN 隧道在节点间传输流量。
#
# 使用方法:
#   kubectl apply -f subnet.yaml
#
# 验证:
#   kubectl get subnet pod-subnet -o wide
#   kubectl describe subnet pod-subnet

apiVersion: network.zstack.io/v1
kind: Subnet
metadata:
  name: pod-subnet
  labels:
    network-type: overlay
spec:
  # IP 范围 (CIDR 格式)
  # 所有 Pod 将从此范围获取 IP 地址
  cidr: "10.244.0.0/16"
  
  # 网关 IP
  # 通常是子网的第一个可用 IP
  gateway: "10.244.0.1"
  
  # 排除的 IP 地址
  # 这些 IP 不会被分配给 Pod
  # 支持单个 IP 和 IP 范围
  excludeIPs:
    - "10.244.0.1"              # 网关 IP
    - "10.244.0.2-10.244.0.10"  # 保留 IP 范围
  
  # IP 协议版本
  # 支持: IPv4, IPv6, Dual
  protocol: IPv4

---
# Example: 多子网配置
# 可以创建多个子网用于不同用途

apiVersion: network.zstack.io/v1
kind: Subnet
metadata:
  name: app-subnet
  labels:
    network-type: overlay
    purpose: application
spec:
  cidr: "10.245.0.0/16"
  gateway: "10.245.0.1"
  excludeIPs:
    - "10.245.0.1"
  protocol: IPv4

---
apiVersion: network.zstack.io/v1
kind: Subnet
metadata:
  name: db-subnet
  labels:
    network-type: overlay
    purpose: database
spec:
  cidr: "10.246.0.0/16"
  gateway: "10.246.0.1"
  excludeIPs:
    - "10.246.0.1"
  protocol: IPv4
